Diagrams
ucudal/ANDIS_Conceptos pull request #32
Opened 2024-05-09 22:56 UTC by fmachadopiriz

2024-05-10 21:38 UTC, PaoloMazza1204 requested changes
¡Está excelente todo 🚀 👏🏻 :shipit:!

Dejo unos comentarios con detalles, nada más.

2024-05-10 21:38 UTC, PaoloMazza1204 commented on 2_Tecnicas_y_herramientas/2_4_1_Diagramas_de_actividades_UML.md
> +actividades terminan, se realiza la actividad `Hornear la receta`, es decir, se
En el diagrama quedó como `Hornear receta`.
```suggestion
actividades terminan, se realiza la actividad `Hornear receta`, es decir, se
```

2024-05-10 21:38 UTC, PaoloMazza1204 commented on 2_Tecnicas_y_herramientas/2_4_1_Diagramas_de_actividades_UML.md
> +posible mostrar participante que realiza cada actividad, utilizando particiones.
```suggestion
posible mostrar el participante que realiza cada actividad, utilizando particiones.
```

2024-05-10 21:38 UTC, PaoloMazza1204 commented on 2_Tecnicas_y_herramientas/2_4_1_Diagramas_de_actividades_UML.md
> +realiza `Tomar pedido`. Luego la cocina realiza `Preparar pedido`. Luego el modo
```suggestion
realiza `Tomar pedido`. Luego la cocina realiza `Preparar pedido`. Luego el mozo
```

2024-05-10 21:38 UTC, PaoloMazza1204 commented on 2_Tecnicas_y_herramientas/2_4_1_Diagramas_de_actividades_UML.md
> +confirma el pedido al restaurante, ni como el restaurante hace llegar la cena al
```suggestion
confirma el pedido al restaurante, ni cómo el restaurante hace llegar la cena al
```

2024-05-10 21:38 UTC, PaoloMazza1204 commented on 2_Tecnicas_y_herramientas/2_4_2_Diagramas_de_casos_de_uso.md
> +## 2.4 Modelos de procesos
Igual que el otro doc:
```suggestion
## 2.4 Modelos de comportamiento
```

2024-05-10 21:38 UTC, PaoloMazza1204 commented on 2_Tecnicas_y_herramientas/2_4_2_Diagramas_de_casos_de_uso.md
> +y [Lucidchart] (https://www.lucidchart.com/pages/uml-use-case-diagram).
```suggestion
y [Lucidchart](https://www.lucidchart.com/pages/uml-use-case-diagram).
```

2024-05-10 21:38 UTC, PaoloMazza1204 commented on 2_Tecnicas_y_herramientas/2_4_2_Diagramas_de_casos_de_uso.md
> +  con un rectángulo con los casos de uso dentro y los actores fuera de él.
Una idea que tengo en mi subconsciente y que puede ser valioso aclarar acá: los actores primarios van siempre a la izquierda y los secundarios a la derecha, ¿no? Si esto es así, podríamos aclararlo acá explícitamente.

2024-05-13 18:15 UTC, fmachadopiriz commented on 2_Tecnicas_y_herramientas/2_4_2_Diagramas_de_casos_de_uso.md
> +  con un rectángulo con los casos de uso dentro y los actores fuera de él.
Correcto, lo agregué

2024-05-13 18:16 UTC, fmachadopiriz commented on 2_Tecnicas_y_herramientas/2_4_2_Diagramas_de_casos_de_uso.md
> +y [Lucidchart] (https://www.lucidchart.com/pages/uml-use-case-diagram).
Raro que esto no sea detectado por el linter...

2024-05-13 18:17 UTC, fmachadopiriz reviewed
Creo que estaría todo.

2024-05-13 20:21 UTC, PaoloMazza1204 commented on 2_Tecnicas_y_herramientas/2_4_3_Diagramas_de_secuencia_UML.md
> +### 2.4.2 Diagramas de secuencia UML
```suggestion
### 2.4.3 Diagramas de secuencia UML
```

2024-05-13 20:21 UTC, PaoloMazza1204 commented on 2_Tecnicas_y_herramientas/2_4_3_Diagramas_de_secuencia_UML.md
> +* Condicionales —*alt*, *alt-else*, *case*: Los mensajes en la región se
```suggestion
* Condicionales —*alt*, *alt-else*, *case*—: Los mensajes en la región se
```

2024-05-13 20:24 UTC, fmachadopiriz reviewed
Done!

2024-05-13 20:25 UTC, PaoloMazza1204 approved these changes

2024-05-13 20:27 UTC, merged