Task: Summary tables
ucudal/ANDIS_Conceptos pull request #85
Opened 2024-08-01 20:31 UTC by mazzapao

## Contenido del *draft* PR hasta el momento

Además de arreglar algunos *nitpicks* que encontré por ahí, este PR agrega tablas que resumen cada entrega del proyecto. La idea de estas tablas es presentar de forma resumida lo requerido para cada entrega del PFG, así que se encuentran en la última sección de `1__Entregable_proyecto.md`: "Entregas del proyecto final de grado".

## Temas abiertos a discusión

1. Se podría incluir algo más para aclarar qué parte específicamente del documento debe ir para cada entrega. Podemos utilizar por ejemplo otra etiqueta para no solo ordenar las partes por obligatoriedad, sino también por entrega como segundo criterio de orden. Esto daría un poco más de granularidad en cuánto a qué parte de cada sección va incluida en cada una de las entregas. 

2. Cualquier comentario respecto a las tablas es recibido. Si no convencen, podemos terminar usando un diagrama o algo más abstracto, por ejemplo.

3. Actualmente, las entregas están separadas cada una con su sección. Quizá sería valioso agregar además un diagrama a alto nivel con las diferentes etapas o entregas del proyecto —o, ambas al mismo tiempo—, para que los equipos tengan una idea general de cómo sería el cronograma del proyecto y su orden.

2024-08-05 22:50 UTC, fmachadopiriz commented on 1_Entregable_proyecto/1__Entregable_proyecto.md
Deberíamos ser consistentes y usar siempre "requerimientos" o siempre "requisitos" —yo puedo haber introducido ambos—. Creo que en el resto es más común encontrar "requerimientos", si fuera así dejaría ese.

2024-08-15 12:04 UTC, fmachadopiriz commented on 1_Entregable_proyecto/1__Entregable_proyecto.md
> +| Todos los eventos del negocio  | Arquitectura detallada con tecnologías usadas por cada componente | Código funcionando con lo implementado hasta el momento | Tests unitarios para las funcionalidad
Aclará por favor que es eventos, casos de uso del negocio, del producto, y requerimientos atómicos de la funcionalidad incluida en el release; de lo contrario queda la sensación de que es sobre el producto completo

2024-08-15 12:08 UTC, fmachadopiriz commented on 1_Entregable_proyecto/1__Entregable_proyecto.md
> +| Requisitos | Diseño y Arquitectura | Desarrollo | Aseguramiento de la Calidad | UX/UI | Gestión y Proceso |
Transpondría las tablas para que quede una primera columna con las dimensiones, ¿qué te parece? Además pondría "No aplicable" o algo por el estilo para los casos que no tienen que agregar nada.

2024-08-15 12:09 UTC, fmachadopiriz requested changes
Hola Paolo, perdón que dejé esto para atrás por el comienzo del semestre que me tuvo ocupado en otras cosas. Te dejé nos comentarios para que revises cuando puedas. Abrazo

2024-08-15 22:11 UTC, mazzapao commented on 1_Entregable_proyecto/1__Entregable_proyecto.md
Bien, de acuerdo 👍🏻. Me encargo de homogeneizar esto.

2024-08-15 22:11 UTC, mazzapao commented on 1_Entregable_proyecto/1__Entregable_proyecto.md
> +| Todos los eventos del negocio  | Arquitectura detallada con tecnologías usadas por cada componente | Código funcionando con lo implementado hasta el momento | Tests unitarios para las funcionalidad
Perfecto, lo ajusto.

2024-08-15 22:12 UTC, mazzapao commented on 1_Entregable_proyecto/1__Entregable_proyecto.md
> +| Requisitos | Diseño y Arquitectura | Desarrollo | Aseguramiento de la Calidad | UX/UI | Gestión y Proceso |
Ah bien, lo ajusto para que quede de esa manera, sí.

2024-08-18 19:36 UTC, mazzapao commented on 1_Entregable_proyecto/1__Entregable_proyecto.md
Cambié las ocurrencias de requisito/s a requerimiento/s

2024-08-18 19:57 UTC, mazzapao commented on 1_Entregable_proyecto/1__Entregable_proyecto.md
> +| Todos los eventos del negocio  | Arquitectura detallada con tecnologías usadas por cada componente | Código funcionando con lo implementado hasta el momento | Tests unitarios para las funcionalidad
Ajusté para aclarar que se refiere a los casos de uso del negocio, del producto y requerimientos atómicos de las funcionalidades implementadas en cada release. Los eventos del negocio sí que los dejé como estaba ("todos los eventos del negocio") porque ya a partir del primer release deberían estar todos prontos, no?

2024-08-19 19:11 UTC, fmachadopiriz approved these changes
Excelente Paolo!

2024-08-21 20:47 UTC, merged